/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';
import 'ionicons';


export namespace Components {

  interface AppCadastroCustomer {
    'address': string;
    'email': string;
    'name': string;
    'open': boolean;
    'pass': string;
    'placeholders': any;
  }
  interface AppCadastroCustomerAttributes extends StencilHTMLAttributes {
    'address'?: string;
    'email'?: string;
    'name'?: string;
    'open'?: boolean;
    'pass'?: string;
    'placeholders'?: any;
  }

  interface AppCadastroItem {
    'desc': string;
    'name': string;
    'open': boolean;
    'price': string;
  }
  interface AppCadastroItemAttributes extends StencilHTMLAttributes {
    'desc'?: string;
    'name'?: string;
    'onCreateUser'?: (event: CustomEvent) => void;
    'open'?: boolean;
    'price'?: string;
  }

  interface AppFab {}
  interface AppFabAttributes extends StencilHTMLAttributes {
    'onOpenModal'?: (event: CustomEvent) => void;
  }

  interface AppHeader {
    'isHome': boolean;
    'name': string;
  }
  interface AppHeaderAttributes extends StencilHTMLAttributes {
    'isHome'?: boolean;
    'name'?: string;
  }

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppCadastroCustomer': Components.AppCadastroCustomer;
    'AppCadastroItem': Components.AppCadastroItem;
    'AppFab': Components.AppFab;
    'AppHeader': Components.AppHeader;
    'AppHome': Components.AppHome;
    'AppRoot': Components.AppRoot;
  }

  interface StencilIntrinsicElements {
    'app-cadastro-customer': Components.AppCadastroCustomerAttributes;
    'app-cadastro-item': Components.AppCadastroItemAttributes;
    'app-fab': Components.AppFabAttributes;
    'app-header': Components.AppHeaderAttributes;
    'app-home': Components.AppHomeAttributes;
    'app-root': Components.AppRootAttributes;
  }


  interface HTMLAppCadastroCustomerElement extends Components.AppCadastroCustomer, HTMLStencilElement {}
  var HTMLAppCadastroCustomerElement: {
    prototype: HTMLAppCadastroCustomerElement;
    new (): HTMLAppCadastroCustomerElement;
  };

  interface HTMLAppCadastroItemElement extends Components.AppCadastroItem, HTMLStencilElement {}
  var HTMLAppCadastroItemElement: {
    prototype: HTMLAppCadastroItemElement;
    new (): HTMLAppCadastroItemElement;
  };

  interface HTMLAppFabElement extends Components.AppFab, HTMLStencilElement {}
  var HTMLAppFabElement: {
    prototype: HTMLAppFabElement;
    new (): HTMLAppFabElement;
  };

  interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {}
  var HTMLAppHeaderElement: {
    prototype: HTMLAppHeaderElement;
    new (): HTMLAppHeaderElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLElementTagNameMap {
    'app-cadastro-customer': HTMLAppCadastroCustomerElement
    'app-cadastro-item': HTMLAppCadastroItemElement
    'app-fab': HTMLAppFabElement
    'app-header': HTMLAppHeaderElement
    'app-home': HTMLAppHomeElement
    'app-root': HTMLAppRootElement
  }

  interface ElementTagNameMap {
    'app-cadastro-customer': HTMLAppCadastroCustomerElement;
    'app-cadastro-item': HTMLAppCadastroItemElement;
    'app-fab': HTMLAppFabElement;
    'app-header': HTMLAppHeaderElement;
    'app-home': HTMLAppHomeElement;
    'app-root': HTMLAppRootElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
